### ISSUE TITLE
how about mac

### ISSUE THREAD

**Issue by hbsun2113** [lagerspetz/linux-stuff#2]
how about mac?

**Comment by lagerspetz** [comment]
Hi,
I currently only have Linux computers that I work with. That said, the scripts in the scripts folder could work on a mac too, but you would need to change a few things such as the location of the trash folder for saferm.sh etc.

If you feel like it, please fork this repo and make a PR with some mac scripts; for example a mac subfolder in the top of the repo and anything under it would be fine with me.
