### ISSUE TITLE
saferm

### ISSUE THREAD

**Issue by MichaelRichardLei** [lagerspetz/linux-stuff#3]
Hi, thanks for your tool **saferm**, it is very useful to me. 
But what about cleaning the Trash file? I use linux on server so I can only use command, it's not convenient to clean files one by one. Thank you very much.

**Comment by lagerspetz** [comment]
After aliasing rm to saferm, I just do
`rm -rfu ~/Trash`
or if you use one of the desktop environments,
`rm -rfu ~/.local/share/Trash`
The -u flag is for unsafe delete (actual rm instead of mv).

**Comment by MichaelRichardLei** [comment]
I got that, thanks! :D
