### ISSUE TITLE
elementary os 中 saferm.sh 未识别桌面进程

### ISSUE THREAD

**Issue by pingxin403** [lagerspetz/linux-stuff#4]
解决方法：修改
` ps -U $USER | grep -E "gnome-settings|startkde|mate-session|mate-settings|mate-panel|gnome-shell|lxsession|unity"`
为`ps -U $USER | grep -E "gnome-settings|startkde|mate-session|mate-settings|mate-panel|gnome-shell|lxsession|unity|pantheon"`

**Comment by lagerspetz** [comment]
You could make a PR like this: https://github.com/lagerspetz/linux-stuff/pull/5
