### ISSUE TITLE
[Question - saferm] What about sudo rm?

### ISSUE THREAD

**Issue by MostHated** [lagerspetz/linux-stuff#6]
Hey there,
    I really like the idea of saferm, as an accidental system goof not long ago is what sent me looking for a solution to this in the first place. The thing is, though, normal rm is not what gave me issues, it would be sudo rm. I followed the instructions posted [on this site](https://www.2daygeek.com/rm-command-to-move-files-to-trash-can-rm-alias/), but noticed it would do nothing for sudo.

From there I did `sudo -i` and then added the alias to the .bashrc, exited from the session back to my terminal, closed it out, then did touch test.sh, followed by `sudo rm -rf test.sh` to see if it would work. I then ran `sudo find / -xdev -name "test.sh"`, but that didn't come back with the expected results of locating the test.sh file I just removed. 

Is there a step I might have missed, or will this just not work with `sudo rm`? That is the one I am most worried about protecting myself from, lol.

Thanks,
-MH

**Comment by MostHated** [comment]
Actually, moments after I posted this, I figured it out. Sorry to bother.

adding `alias sudo='sudo '` allows it to work as I expected without interfering with normal `sudo` operation.

![](https://i.imgur.com/PqAS2Bk.png)

**Comment by lagerspetz-lempea** [comment]
Hi, thanks for the solution. I will add it to readme.

**Comment by lagerspetz** [comment]
Hi, thanks for the solution. I have added it to readme.
