### ISSUE TITLE
Not working correctly on Manjaro KDE

### ISSUE THREAD

**Issue by Milliw** [lagerspetz/linux-stuff#7]
Seems not to detect the (new?) KDE Plasma??
Adding "plasma" to line 36 makes it using the right trash path on my system.

Not sure if this is the right way but it works for me.
Oh, and "last update" date is way behind ;)

**Comment by lagerspetz** [comment]
Hi,
I had to fix some ineffective parsing of yes/no answers in some cases, and added plasma at the same time. Just to let you know, even though this ticket is "slightly" old :)
